

name=input("What's your name?")
print(f"Hello {name} ready for a joke?")
input("")
print("Lets go!")
input("")

print("What do you call an alligator wearing a vest?")
input("")
print("An investigator!")
input("")
print("What to hear another one?")
input("")
print("I only answered 9 questions on my test")
input("")
print("why?")
input("")
print("Because Hamilton wrote the other 51!")
input("")
print("That was funny!")
input("")
print("Ok, ok one more!")
input("")
print("Why don't scientists trust atoms?")
input("")
print("Because they make up everything!")
input("")
print("Thanks for listening to my jokes")
input("")
print("See you on the other side of the war!")