name=input("Hi what is your name?")
input("")
print(f"Hello {name}, and welcome to my mad lib!")
input("")
print("Rules: Only put capitals in STORE, DRINK, PERSON, and LOCATION! NO SPACES!")
person=input("Give me a person (capitalize the first letter).")
input("")
location=input("Give me a location (capitalize the first letter).")
input("")
food=input("Give me a food (DON'T capitalize the first letter).")
input("")
drink=input("Give me a drink (capitalize the first letter).")
input("")
store=input("Give me a grocery store (capitalize the first letter).")
input("")
number=input("Give me a big number(Don't put a $ sign).")
print("Now it's time for the story!")
print(f"Once upon a time there was a person named {person} who lived in {location}, and they loved to eat {food}.")
input("")
print(f"Every day {person} would eat {food}, for breakfast, lunch, snack, and dinner.")
input("")
print(f"{person} wanted some more {food}, so they decided to go to {store} to get some {food}.")
input("")
print(f"When {person} got to {store} they didn't see any {food}. They wanted to talk to the manger to ask about where the {food} is")
input("")
print(f"The manager said that they ran out of {food}. {person} was really sad that there was no more {food}.")
input("")
print(f"On the way home {person} stopped for some {drink}. They asked the restaurant if there was any {food}")
input("")
print(f"They said that there was one last plate of {food}...but it cost {number} dollars!")
input("")
print(f"{person} didn't have enough money to buy it so they got in their car and went home.")
input("")
print(f"Once {person} got home they decided to sign up as a food critic")
input("")
print(f"Now {person} will never run out of food ever again.")
input("")
print("The End!")